version: '3.9'
services:
 backend:
    build: .
    restart: always
    ports:
      - 3002:3002
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=5432
      - DB_USER=postgres
      - DB_PASS=123
      - DB_HOST=db
      - DB_NAME=clients_database
      - DB_PORT=5432
 db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
      - POSTGRES_DB=clients_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE
 adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
